#!/usr/bin/env python

from util.benchmark import benchmark

problem = "2. Even Fibonacci numbers"
"""
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""


def solve():
    """Even Fibonacci numbers"""
    sum, a, b = 0, 1, 2
    while b < 4000000:
        sum += b
        # a(odd), b(even), a+b(odd), a+2b(odd), 2a+3b(even)
        a, b = a + 2 * b, 2 * a + 3 * b
    return sum

if __name__ == '__main__':
    benchmark(problem, solve)
